<a href="https://colab.research.google.com/github/ricardodhuelsmann/python_bibliotecas/blob/main/Pandas/4_Agrupamentos_e_estat%C3%ADsticas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas
###Cálculos e variáveis estatísticas

In [ ]:
import pandas as pd
df = pd.read_csv('pokemon_dados_modificados.csv')

###Função 'Groupby'

In [ ]:
#Classificar os valores de acordo com o Tipo, apresentando a média de cada parâmetro
df.groupby(['Type 1']).mean()

                   #       Total         HP  ...       Speed  Generation  Legendary
Type 1                                       ...
Bug       334.492754  378.927536  56.884058  ...   61.681159    3.217391   0.000000
Dark      461.354839  445.741935  66.806452  ...   76.161290    4.032258   0.064516
Dragon    474.375000  550.531250  83.312500  ...   83.031250    3.875000   0.375000
Electric  363.500000  443.409091  59.795455  ...   84.500000    3.272727   0.090909
Fairy     449.529412  413.176471  74.117647  ...   48.588235    4.117647   0.058824
Fighting  363.851852  416.444444  69.851852  ...   66.074074    3.370370   0.000000
Fire      327.403846  458.076923  69.903846  ...   74.442308    3.211538   0.096154
Flying    677.750000  485.000000  70.750000  ...  102.500000    5.500000   0.500000
Ghost     486.500000  439.562500  64.437500  ...   64.343750    4.187500   0.062500
Grass     344.871429  421.142857  67.271429  ...   61.928571    3.357143   0.042857
Ground    356.281250  437.500000  73.781250  ...   63.906250    3.156250   0.125000
Ice       423.541667  433.458333  72.000000  ...   63.458333    3.541667   0.083333
Normal    319.173469  401.683673  77.275510  ...   71.551020    3.051020   0.020408
Poison    251.785714  399.142857  67.250000  ...   63.571429    2.535714   0.000000
Psychic   380.807018  475.947368  70.631579  ...   81.491228    3.385965   0.245614
Rock      392.727273  453.750000  65.363636  ...   55.909091    3.454545   0.090909
Steel     442.851852  487.703704  65.222222  ...   55.259259    3.851852   0.148148
Water     303.089286  430.455357  72.062500  ...   65.964286    2.857143   0.035714

[18 rows x 10 columns]

In [ ]:
#Classificar os valores de acordo com o Tipo 2, apresentando a média de cada parâmetro, em ordem descrecente de ataque
df.groupby(['Type 2']).mean().sort_values('Attack', ascending=False)

                   #       Total         HP  ...      Speed  Generation  Legendary
Type 2                                       ...
Fighting  438.192308  525.846154  79.461538  ...  87.384615    3.923077   0.153846
Dark      413.850000  484.400000  75.550000  ...  75.350000    3.750000   0.050000
Ice       441.285714  525.714286  90.000000  ...  74.642857    3.714286   0.214286
Dragon    482.555556  526.166667  82.166667  ...  80.555556    4.166667   0.222222
Steel     435.636364  485.227273  64.636364  ...  59.363636    3.818182   0.045455
Bug       382.000000  393.333333  53.333333  ...  61.666667    3.333333   0.000000
Ground    307.600000  444.342857  77.228571  ...  54.657143    2.942857   0.028571
Ghost     551.714286  430.714286  59.142857  ...  53.857143    4.785714   0.071429
Rock      347.785714  434.642857  68.071429  ...  36.000000    3.142857   0.000000
Fire      481.833333  506.250000  71.250000  ...  79.666667    4.000000   0.250000
Flying    331.103093  452.546392  71.391753  ...  85.721649    3.072165   0.134021
Psychic   337.151515  479.060606  72.212121  ...  69.484848    2.939394   0.151515
Grass     505.400000  408.920000  62.640000  ...  57.320000    4.480000   0.000000
Electric  465.666667  455.333333  88.166667  ...  71.500000    4.000000   0.166667
Water     400.000000  418.214286  62.714286  ...  57.142857    3.428571   0.071429
Poison    169.970588  396.500000  58.764706  ...  66.647059    1.970588   0.000000
Fairy     379.043478  417.956522  64.304348  ...  61.217391    3.565217   0.086957
Normal    681.000000  411.500000  63.500000  ...  89.250000    6.000000   0.000000

[18 rows x 10 columns]

In [ ]:
#Classificar e contar por determinado parâmetro

df['Contador'] = 1
resumo_t1 = df.groupby(['Type 1']).count().sort_values('Contador', ascending=False)['Contador']
print(resumo_t1)

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Ghost        32
Ground       32
Dragon       32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: Contador, dtype: int64

In [ ]:
#Classificar e agrupar de acordo com grupo dentro de grupo
resumo_t1_t2 = df.groupby(['Type 1', 'Type 2']).count()['Contador']
print(resumo_t1_t2)

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: Contador, Length: 136, dtype: int64